import { Address } from "./Address";
import { Customer } from "./Customer";
import { LineItem } from "./LineItem";
import { MoneySet } from "./Money";

export interface Order {
  id: number;
  name: string;
  note: string | null;
  tags: string;
  test: boolean;
  email: string;
  phone: string | null;
  token: string;
  app_id: number;
  number: number;
  gateway: string;
  refunds: any[];
  user_id: string | null;
  currency: string;
  customer: Customer;
  closed_at: string | null;
  confirmed: boolean;
  device_id: string | null;
  reference: string | null;
  tax_lines: any[];
  total_tax: string;
  browser_ip: string | null;
  cart_token: string | null;
  created_at: string;
  line_items: LineItem[];
  source_url: string | null;
  updated_at: string;
  checkout_id: string | null;
  location_id: string | null;
  total_line_items_price: string;
  discount_codes: any[];
  total_discounts: string;
  billing_address: Address;
  shipping_address: Address;
  subtotal_price: string;
  total_price: string;
  total_tip_received: string;
  total_weight: number;
  fulfillment_status: string | null;
  order_status_url: string;
  admin_graphql_api_id: string;
  total_price_usd: string;
  processed_at: string;
  line_items_subtotal_price: string;
  shipping_lines: any[];
  total_refunds: string;
  checkout_token: string | null;
  total_shipping_price_set: MoneySet;
  subtotal_price_set: MoneySet;
  total_price_set: MoneySet;
  total_tax_set: MoneySet;
  cancel_reason: string | null;
  financial_status: string;
  total_line_items_price_set: MoneySet;
}
